services:

  web:
    image: web-docker
    container_name: web-docker
    build: app/aspnetapp
    ports:
      - 8080:80
    restart: always
    #volumes:
    #  - web-docker-vol:/app/wwwroot/images

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: db-docker
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: example_123
    restart: always
      
#volumes:
#  web-docker-vol:        
