## Dockerfile best practices:
##https://docs.docker.com/develop/develop-images/instructions/
## https://hub.docker.com/_/microsoft-dotnet-aspnet
## https://hub.docker.com/_/alpine
##FROM mcr.microsoft.com/dotnet/aspnet:5.0 as base

# 1 rule
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app

##FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
# 1 rule
FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
COPY . /src
WORKDIR /src

RUN dotnet build "aspnetapp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "aspnetapp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

## Install ps command
##RUN apt update -y 
##RUN apt-get install --reinstall procps net-tools -y
# 2 rule
RUN apk update \
        && apk add procps \
        net-tools \
        && rm -rf /var/lib/apt/lists/*

## Good practices

# 3 rule
## 
ENV APP_USER web_user
## Set new user, no root on image
# 4 rule
RUN useradd -r $APP_USER
USER $APP_USER

COPY --from=publish /app/publish .
# 5 rule
EXPOSE 8080
ENTRYPOINT ["dotnet", "aspnetapp.dll"]
